# Flag di debug
#DEBUG = False
DEBUG = True
DEBUG_VERBOSE = False

# DKP SETTINGS
MINIMUM_DKP_POINTS_PER_ITEM = 1
MAX_REQUEST_ITEMS_NORMAL = 3
MAX_REQUEST_ITEMS_ARCHBOSS = 1

#DISCORD SETTINGS
DISCORD_INTERACTION_TIMEOUT = 180

EASTER_EGG = True